default-server: SERVER_ID

channel-ids:
  first-join:
    - CHANNEL_ID                      # Primary channel
    - OTHER_SERVER_ID:CHANNEL_ID      # Cross-server channel

  join:
    - CHANNEL_ID
    - OTHER_SERVER_ID:CHANNEL_ID

  quit:
    - CHANNEL_ID
    - OTHER_SERVER_ID:CHANNEL_ID

  global-chat:
    - CHANNEL_ID
    - OTHER_SERVER_ID:CHANNEL_ID

  advancements:
    - CHANNEL_ID
    - OTHER_SERVER_ID:CHANNEL_ID

messages:
  first-join:
    text: ''
    embed:
      enabled: true
      color: YELLOW
      author:
        name: 'Made by CroaBeast'
        url: 'https://www.spigotmc.org/resources/96378/'
        iconURL: 'https://crafatar.com/avatars/{UUID}'
      thumbnail: 'https://crafatar.com/avatars/{UUID}'
      title:
        text: 'S.I.R. - Chat Plugin'
        url: ''
      description: ':bell: `{player} has join the server for the first time`'
      timeStamp: true

  join:
    text: ''
    embed:
      enabled: true
      color: GREEN
      author:
        name: 'Made by CroaBeast'
        url: 'https://www.spigotmc.org/resources/96378/'
        iconURL: 'https://crafatar.com/avatars/{UUID}'
      thumbnail: 'https://crafatar.com/avatars/{UUID}'
      title: 'S.I.R. - Chat Plugin'
      description: ':white_check_mark: `{player} has join the server`:bangbang:'
      timeStamp: true

  quit:
    text: ':x: `{player} has left the server` :broken_heart:'
    embed:
      enabled: false
      color: RED
      author:
        name: ''
        url: ''
        iconURL: ''
      thumbnail: ''
      title: ''
      description: ''
      timeStamp: true

  global-chat:
    text: '**{prefix}** {player} `{suffix}` :white_small_square: {message}'

  advancements:
    text: '**{player}** has complete the {frame-lower-case}: **{advancement}**'
