# Chat System Configuration
update: true

# Default Format Settings
# This option allows you to enable or disable compatibility
# with other plugins that use default bukkit chat format.
# If enabled, the chat will use the default Bukkit format, not
# recommended.
default-format: false

# Muted Player Control message
# This message is sent to players who are muted whn they try
# to send a message.
is-muted: "<P> &cYou are muted, you can not send messages."

# Empty Message Control
# Keeping this disabled is recommended to prevent chat spam
allow-empty:
  # Allow messages with only spaces
  enabled: false

  # Error message
  message: '<P> &cYou can not send an empty message.'

# Console Log Format
# Note: Affects ALL channel formats in console
simple-logger:
  # Use simplified logger format
  enabled: false

  # Custom console format
  # Supports: PlaceholderAPI and available placeholders
  format: ' &7{player}: {message}'

# Available Placeholders:
# {player}  - Player name
# {message} - Chat message
# {prefix}  - Player prefix
# {suffix}  - Player suffix
# {color-start} - Color start tag
# {color-end}   - Color end tag